variables:
    IMAGE_NAME: helenhaveloh/flask-gitlab
    IMAGE_TAG: python-app-1.0


run_tests:
    image: python:3.12.3-bookworm
    before_script:
        - apt-get update && apt-get install make
    script:
        - make test

build_image:
    image: docker:26.1.0
    services:
        - docker:26.1.0-dind
    variables:
        DOCKER_TLS_CERTDIR: "/certs"
    before_script:
        - docker login -u $DOCKER_USERNAME -p $DOCKER_TOKEN 
    script:
        - docker build -t $IMAGE_NAME:$IMAGE_TAG .
        - docker push $IMAGE_NAME:$IMAGE_TAG